# Define your admin routes here
app_events:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\EventController
    name_prefix: app.
    options:
        expose: true

app_rooms:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\RoomController
    name_prefix: app.
    options:
        expose: true

app_timeline:
    type: rest
    prefix: /admin/api
    resource: App\Api\Controller\TimelineController
    name_prefix: app.
    options:
        expose: true

app_promos:
    type: rest
    prefix: /admin/api
    resource: App\Controller\Admin\PromoController
    name_prefix: app.
    options:
        expose: true
